### ISSUE TITLE
missing 2 input boxes and cant change how many calculations it does

### ISSUE THREAD

**Issue by zabero** [Zarroc2762/E7-Gear-Optimizer#22]
[http://prntscr.com/p7e138](url)

**Comment by Zarroc2762** [comment]
Regarding the missing boxes:
There are no missing boxes. Filters filter calculated results and force values exclude items which do not meet these values before the calculation. There won't be any force boxes for DMG, EHP, DMG/SPD, EHP/SPD and HP/SPD, since they are calculated stats which do not occur on items.

Regarding the caluclation limit:
I guess you used AlexeiA's preview version. Not all of his features were merged into this yet. We are working on it.

**Comment by Zarroc2762** [comment]
This feature was included in https://github.com/Zarroc2762/E7-Gear-Optimizer/releases/tag/v2.7
